/* Project : 2050 — service worker (offline play). Generated by build.py; do not edit by hand. */
const CORE = "p2050-core-ed067fafdb";      // page, manifest, icons, three.js — changes with every build
const MEDIA = "p2050-media-4fd87a32eb";   // audio + tutorial images — only changes when those files change
const FONTS = "p2050-fonts-v1";
const CORE_FILES = ["./", "./index.html", "site.webmanifest", "assets/lib/three.min.js", "favicon.svg", "icon-16.png", "icon-32.png", "icon-192.png", "icon-512.png", "apple-touch-icon.png"];
const MEDIA_FILES = ["assets/audio/amb-air.mp3", "assets/audio/amb-arctic.mp3", "assets/audio/amb-bees.mp3", "assets/audio/amb-birds.mp3", "assets/audio/amb-city.mp3", "assets/audio/amb-construction.mp3", "assets/audio/amb-crowd.mp3", "assets/audio/amb-explosion.mp3", "assets/audio/amb-factory.mp3", "assets/audio/amb-farm.mp3", "assets/audio/amb-fire.mp3", "assets/audio/amb-flood.mp3", "assets/audio/amb-forest.mp3", "assets/audio/amb-harbor.mp3", "assets/audio/amb-heat.mp3", "assets/audio/amb-lab.mp3", "assets/audio/amb-market.mp3", "assets/audio/amb-ocean.mp3", "assets/audio/amb-office.mp3", "assets/audio/amb-siren.mp3", "assets/audio/amb-storm.mp3", "assets/audio/amb-train.mp3", "assets/audio/amb-underwater.mp3", "assets/audio/amb-wind.mp3", "assets/audio/music-game1.mp3", "assets/audio/music-game2.mp3", "assets/audio/music-menu.mp3", "assets/audio/sfx-action.mp3", "assets/audio/sfx-aid.mp3", "assets/audio/sfx-buy.mp3", "assets/audio/sfx-choose.mp3", "assets/audio/sfx-click.mp3", "assets/audio/sfx-close.mp3", "assets/audio/sfx-done.mp3", "assets/audio/sfx-error.mp3", "assets/audio/sfx-event.mp3", "assets/audio/sfx-lose.mp3", "assets/audio/sfx-miss.mp3", "assets/audio/sfx-news.mp3", "assets/audio/sfx-open.mp3", "assets/audio/sfx-pause.mp3", "assets/audio/sfx-pop.mp3", "assets/audio/sfx-save.mp3", "assets/audio/sfx-select.mp3", "assets/audio/sfx-spawnGreen.mp3", "assets/audio/sfx-spawnRed.mp3", "assets/audio/sfx-speed.mp3", "assets/audio/sfx-start.mp3", "assets/audio/sfx-warn.mp3", "assets/audio/sfx-win.mp3", "assets/audio/sfx-year.mp3", "assets/tutorial/t1-goal.jpg", "assets/tutorial/t2-meters.jpg", "assets/tutorial/t3-resources.jpg", "assets/tutorial/t4-regions.jpg", "assets/tutorial/t5-bubbles.jpg", "assets/tutorial/t6-tree.jpg", "assets/tutorial/t7-event.jpg", "assets/tutorial/t8-win.jpg"];
const FONT_CSS = "https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@500;600;700&family=IBM+Plex+Sans+Thai:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500;600&display=swap";

async function fill(name, files){
  const c = await caches.open(name);
  await Promise.all(files.map(async f => { if (!(await c.match(f))) { try { await c.add(f); } catch (e) {} } }));
}
async function cacheFonts(){
  try {
    const c = await caches.open(FONTS);
    if (await c.match(FONT_CSS)) return;
    const r = await fetch(FONT_CSS, { mode: "cors" }); if (!r.ok) return;
    const css = await r.clone().text(); await c.put(FONT_CSS, r);
    const urls = [...new Set((css.match(/https:\/\/fonts\.gstatic\.com\/[^)'"\s]+/g) || []))];
    await Promise.all(urls.map(u => fetch(u, { mode: "cors" }).then(res => res.ok && c.put(u, res)).catch(() => {})));
  } catch (e) {}
}

self.addEventListener("install", e => {
  e.waitUntil(Promise.all([fill(CORE, CORE_FILES), fill(MEDIA, MEDIA_FILES), cacheFonts()]).then(() => self.skipWaiting()));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith("p2050-") && ![CORE, MEDIA, FONTS].includes(k)).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

/* Audio elements send Range requests; answer them from the cached file with a 206 slice. */
async function rangeResponse(req, res){
  const m = /bytes=(\d*)-(\d*)/.exec(req.headers.get("range") || ""); if (!m) return res;
  const buf = await res.arrayBuffer(), size = buf.byteLength;
  const start = m[1] ? +m[1] : Math.max(0, size - +m[2]), end = m[1] && m[2] ? Math.min(+m[2], size - 1) : size - 1;
  return new Response(buf.slice(start, end + 1), { status: 206, statusText: "Partial Content", headers: {
    "Content-Type": res.headers.get("Content-Type") || "audio/mpeg", "Content-Range": `bytes ${start}-${end}/${size}`,
    "Content-Length": String(end - start + 1), "Accept-Ranges": "bytes" } });
}

self.addEventListener("fetch", e => {
  const req = e.request; if (req.method !== "GET") return;
  const url = new URL(req.url);

  // Page: try the network first (gets updates), fall back to the cached copy when offline.
  if (req.mode === "navigate") {
    e.respondWith((async () => {
      try {
        const ctl = new AbortController(), timer = setTimeout(() => ctl.abort(), 4000);
        const r = await fetch(req, { signal: ctl.signal }); clearTimeout(timer);
        if (r.ok) (await caches.open(CORE)).put("./index.html", r.clone());
        return r;
      } catch (err) { return (await caches.match("./index.html")) || (await caches.match("./")) || Response.error(); }
    })());
    return;
  }

  // Google Fonts: cache first.
  if (url.hostname === "fonts.googleapis.com" || url.hostname === "fonts.gstatic.com") {
    e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(r => { if (r.ok || r.type === "opaque") { const cp = r.clone(); caches.open(FONTS).then(c => c.put(req, cp)); } return r; })));
    return;
  }

  // Same-origin files: cache first, then network (and keep a copy).
  if (url.origin === location.origin) {
    e.respondWith((async () => {
      const key = url.pathname.endsWith("/") ? req : new Request(url.href.split("#")[0].split("?")[0]);
      const hit = await caches.match(key, { ignoreSearch: true });
      if (hit) return req.headers.has("range") ? rangeResponse(req, hit) : hit;
      try {
        const r = await fetch(req);
        if (r.ok && r.status === 200) { const cp = r.clone(); caches.open(url.pathname.includes("/assets/") && !url.pathname.includes("/lib/") ? MEDIA : CORE).then(c => c.put(key, cp)); }
        return r;
      } catch (err) { return Response.error(); }
    })());
  }
});
